import React from "react";
import Head from "next/head";
import SecItemBlog from "../../components/SecItemBlog";
import SecSearchCreateBlog from "../../components/SecSearchCreateBlog";
import SecSubscribe from "../../components/SecSubscribe";
import NavbarFooterLayout from "../../layout/NavbarFooterLayout";

export default function BlogPage() {
  return (
    <>
    <NavbarFooterLayout>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SecSearchCreateBlog />
      <SecItemBlog />
      <SecSubscribe />
    </NavbarFooterLayout>
    </>
  );
}
