import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by asd{" "}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <>
    <section className="header relative pt-16 items-center flex h-screen max-h-full">
      <div className="container mx-auto items-center flex flex-wrap z-10">
        <div className="w-full md:w-8/12 lg:w-6/12 xl:w-6/12 px-4">
          <div className="pt-40 sm:pt-0">
            <h2 className="font-bold text-4xl text-white">Community & Support System for 
Women to Shining in Tech-Industry</h2>
          </div>
        </div>
      </div>
      <div
        className="absolute top-0 w-full h-full bg-center bg-cover z-0"
        style={{
          backgroundImage:
            "url('/img/banner.jpg')",
        }}
      >
      </div>
    </section>
    <section className="mt-10 md:mt-20 pb-40 relative">
      <div className="container mx-auto justify-center text-center flex flex-wrap">
        <div className="w-full px-12 md:px-4">
          <h2 className="font-bold text-4xl">ABOUT US</h2>
          <p className="text-lg leading-relaxed mt-4 mb-4 text-blueGray-500">
            FemaleGeek  merupakan sebuah komunitas yang terdiri dari perempuan-perempuan ‘strong‘ yang cinta dan bergelut dalam bidang IT. Bidang yang biasanya di dominasi oleh kaum adam ini kini mulai digeluti oleh kaum hawa.
          </p>
          <p className="text-lg leading-relaxed mt-4 mb-4 text-blueGray-500">
            Tidak hanya terbatas pada bagian IT tertentu, anggota FemaleGeek Indonesia ternyata berasal dari latar belakang yang berbeda seperti IT Support, Software Developer, System Analayst, IT Consultant, Mahasiswi IT dan lainnya untuk membentuk sebuah wadah yang berfokus pada pengembangan perempuan dalam dunia IT.
          </p>
          <p className="text-lg leading-relaxed mt-4 mb-4 text-blueGray-500">
            Komunitas yang dibangun khusus untuk para wanita ini bukan hanya terbatas pada wadah untuk berbagi namun juga sebagai inspirasi kepada semua wanita yang hendak atau sudah berkecimpung dalam dunia IT. menumbuhkan semangat dan saling mendukung dalam kelompok.
          </p>
          <div className="absolute top-0 right-0 pt-4 bg-cover w-10/12 sm:w-6/12">
            <Image 
              src="/img/bg-pink.png"
              alt="Landscape picture"
              width={700}
              height={380}
            />
          </div>
        </div>
        <div className="w-full px-12 md:px-4">
          <div className="grid justify-items-start">
            <h2 className="font-bold text-2xl pt-8">WHAT WE DO</h2>
            <p className="font-semibold text-base pb-6 text-gray-500">Keseharian apa yang kami lakukan.</p>
          </div>
          <div className="w-full grid grid-cols-1 gap-y-6 md:grid-cols-4 md:gap-x-10">
            <div className="w-full p-6 bg-[#EC407A] rounded-lg">
              <div className="flex flex-col items-center">
                <div className="py-2 space-x-4">
                  <Image 
                  src="/img/events.png"
                  alt="Landscape picture"
                  width={80}
                  height={80}
                  />
                </div>
                <div className="py-2 space-x-4">
                  <h2 className="font-bold text-lg text-white">Event</h2>
                </div>
              </div>
            </div>
            <div className="w-full p-6 bg-[#EC407A] rounded-lg">
              <div className="flex flex-col items-center">
                <div className="py-2 space-x-4">
                  <Image 
                  src="/img/kulgram.png"
                  alt="Landscape picture"
                  width={80}
                  height={80}
                  />
                </div>
                <div className="py-2 space-x-4">
                  <h2 className="font-bold text-lg text-white">Kuliah Telegram</h2>
                </div>
              </div>
            </div>
            <div className="w-full p-6 bg-[#EC407A] rounded-lg">
              <div className="flex flex-col items-center">
                <div className="py-2 space-x-4">
                  <Image 
                  src="/img/mentoring.png"
                  alt="Landscape picture"
                  width={80}
                  height={80}
                  />
                </div>
                <div className="py-2 space-x-4">
                  <h2 className="font-bold text-lg text-white">Mentoring</h2>
                </div>
              </div>
            </div>
            <div className="w-full p-6 bg-[#EC407A] rounded-lg">
              <div className="flex flex-col items-center">
                <div className="py-2 space-x-4">
                  <Image 
                  src="/img/volunteer.png"
                  alt="Landscape picture"
                  width={80}
                  height={80}
                  />
                </div>
                <div className="py-2 space-x-4">
                  <h2 className="font-bold text-lg text-white">Volunteer</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </section>
    </>
  );
};

export default Home;
